export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type OrderStatus = "pending" | "confirmed" | "processing" | "completed" | "cancelled";
export type PaymentStatus = "unpaid" | "pending" | "paid" | "refunded";
export type PaymentMethod = "vnpay" | "momo" | "zalopay" | "bank_transfer" | "zalo_manual";
export type InvitationType = "general" | "personal";
export type PackageType = "basic" | "standard" | "premium";
export type RsvpStatus = "pending" | "attending" | "not_attending" | "maybe";

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          full_name: string | null;
          avatar_url: string | null;
          role: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          avatar_url?: string | null;
          role?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]>;
      };
      templates: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          thumbnail_url: string | null;
          preview_url: string | null;
          html_content: string | null;
          css_content: string | null;
          js_content: string | null;
          category: string | null;
          color_scheme: string[] | null;
          tags: string[] | null;
          price_adjustment: number;
          is_active: boolean;
          is_featured: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          thumbnail_url?: string | null;
          preview_url?: string | null;
          html_content?: string | null;
          css_content?: string | null;
          js_content?: string | null;
          category?: string | null;
          color_scheme?: string[] | null;
          tags?: string[] | null;
          price_adjustment?: number;
          is_active?: boolean;
          is_featured?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["templates"]["Insert"]>;
      };
      packages: {
        Row: {
          id: string;
          type: PackageType;
          name: string;
          description: string | null;
          price: number;
          personal_invitation_limit: number;
          features: Json | null;
          is_active: boolean;
          sort_order: number;
        };
        Insert: {
          id?: string;
          type: PackageType;
          name: string;
          description?: string | null;
          price: number;
          personal_invitation_limit?: number;
          features?: Json | null;
          is_active?: boolean;
          sort_order?: number;
        };
        Update: Partial<Database["public"]["Tables"]["packages"]["Insert"]>;
      };
      orders: {
        Row: {
          id: string;
          order_code: string;
          groom_name: string;
          bride_name: string;
          wedding_date: string;
          wedding_time: string | null;
          venue_name: string | null;
          venue_address: string | null;
          venue_maps_url: string | null;
          venue_lat: number | null;
          venue_lng: number | null;
          story: string | null;
          hashtag: string | null;
          music_url: string | null;
          customer_name: string;
          customer_phone: string;
          customer_email: string | null;
          customer_zalo: string | null;
          package_id: string | null;
          template_id: string | null;
          status: OrderStatus;
          payment_status: PaymentStatus;
          payment_method: PaymentMethod | null;
          payment_transaction_id: string | null;
          paid_at: string | null;
          couple_photos: string[] | null;
          total_amount: number | null;
          admin_notes: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          order_code?: string; // Auto-generated by trigger
          groom_name: string;
          bride_name: string;
          wedding_date: string;
          wedding_time?: string | null;
          venue_name?: string | null;
          venue_address?: string | null;
          venue_maps_url?: string | null;
          venue_lat?: number | null;
          venue_lng?: number | null;
          story?: string | null;
          hashtag?: string | null;
          music_url?: string | null;
          customer_name: string;
          customer_phone: string;
          customer_email?: string | null;
          customer_zalo?: string | null;
          package_id?: string | null;
          template_id?: string | null;
          status?: OrderStatus;
          payment_status?: PaymentStatus;
          payment_method?: PaymentMethod | null;
          payment_transaction_id?: string | null;
          paid_at?: string | null;
          couple_photos?: string[] | null;
          total_amount?: number | null;
          admin_notes?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["orders"]["Insert"]>;
      };
      invitations: {
        Row: {
          id: string;
          order_id: string;
          template_id: string | null;
          type: InvitationType;
          url_slug: string;
          guest_name: string | null;
          custom_data: Json | null;
          view_count: number;
          last_viewed_at: string | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          order_id: string;
          template_id?: string | null;
          type?: InvitationType;
          url_slug: string;
          guest_name?: string | null;
          custom_data?: Json | null;
          view_count?: number;
          last_viewed_at?: string | null;
          is_active?: boolean;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["invitations"]["Insert"]>;
      };
      guests: {
        Row: {
          id: string;
          invitation_id: string;
          order_id: string;
          name: string;
          phone: string | null;
          email: string | null;
          rsvp_status: RsvpStatus;
          rsvp_note: string | null;
          guest_count: number;
          responded_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          invitation_id: string;
          order_id: string;
          name: string;
          phone?: string | null;
          email?: string | null;
          rsvp_status?: RsvpStatus;
          rsvp_note?: string | null;
          guest_count?: number;
          responded_at?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["guests"]["Insert"]>;
      };
      media_assets: {
        Row: {
          id: string;
          name: string | null;
          url: string;
          type: string | null;
          size_bytes: number | null;
          linked_to: string | null;
          linked_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name?: string | null;
          url: string;
          type?: string | null;
          size_bytes?: number | null;
          linked_to?: string | null;
          linked_id?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["media_assets"]["Insert"]>;
      };
      cms_content: {
        Row: {
          id: string;
          key: string;
          value: string | null;
          value_json: Json | null;
          type: string;
          label: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          value?: string | null;
          value_json?: Json | null;
          type?: string;
          label?: string | null;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["cms_content"]["Insert"]>;
      };
      testimonials: {
        Row: {
          id: string;
          couple_name: string;
          content: string;
          avatar_url: string | null;
          rating: number;
          wedding_date: string | null;
          is_active: boolean;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          couple_name: string;
          content: string;
          avatar_url?: string | null;
          rating?: number;
          wedding_date?: string | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["testimonials"]["Insert"]>;
      };
    };
    Enums: {
      order_status: OrderStatus;
      payment_status: PaymentStatus;
      payment_method: PaymentMethod;
      invitation_type: InvitationType;
      package_type: PackageType;
      rsvp_status: RsvpStatus;
    };
  };
}

// Convenience row types
export type Profile = Database["public"]["Tables"]["profiles"]["Row"];
export type Template = Database["public"]["Tables"]["templates"]["Row"];
export type Package = Database["public"]["Tables"]["packages"]["Row"];
export type Order = Database["public"]["Tables"]["orders"]["Row"];
export type Invitation = Database["public"]["Tables"]["invitations"]["Row"];
export type Guest = Database["public"]["Tables"]["guests"]["Row"];
export type MediaAsset = Database["public"]["Tables"]["media_assets"]["Row"];
export type CmsContent = Database["public"]["Tables"]["cms_content"]["Row"];
export type Testimonial = Database["public"]["Tables"]["testimonials"]["Row"];
